var HEADERS_TO_STRIP_LOWERCASE = [
    'x-frame-options',
];

chrome.webRequest.onHeadersReceived.addListener(
    function(details) {
        return {
            responseHeaders: details.responseHeaders.filter(function(header) {
                return HEADERS_TO_STRIP_LOWERCASE.indexOf(header.name.toLowerCase()) < 0;
            })
        };
    }, {
        urls: ["*://vtop.vit.ac.in/student/forgot_pswd.asp","*://academicscc.vit.ac.in/registration/ffcs_login.asp","*://academics.vit.ac.in/studpay/","*://vtop.vit.ac.in/faculty/fac_login.asp","*://vtop.vit.ac.in/parent/parent_login.asp","*://vtop.vit.ac.in/student/stud_login.asp","*://vtop.vit.ac.in/faculty/","*://vtop.vit.ac.in/parent/","*://vtop.vit.ac.in/student/","*://academics.vit.ac.in/faculty/fac_login.asp","*://academics.vit.ac.in/parent/parent_login.asp","*://academics.vit.ac.in/student/stud_login.asp","*://academics.vit.ac.in/parent/","*://academics.vit.ac.in/student/","*://academics.vit.ac.in/faculty/","*://27.251.102.132/parent/parent_login.asp","*://27.251.102.132/student/stud_login.asp","*://27.251.102.132/parent/","*://27.251.102.132/student/","*://academicscc.vit.ac.in/student/","*://academicscc.vit.ac.in/student/stud_login.asp","*://academicscc.vit.ac.in/faculty/","*://academicscc.vit.ac.in/faculty/fac_login.asp","*://academicscc.vit.ac.in/parent/","*://academicscc.vit.ac.in/parent/parent_login.asp","*://academicscc.vit.ac.in/feedback/","*://academicscc.vit.ac.in/REGISTRATIONS/FALLSEM201617_WISHLIST/ffcs_login.asp","*://academicscc.vit.ac.in/REGISTRATIONS/FALLSEM201617_PM/ffcs_login.asp","*://academicscc.vit.ac.in/registrations/FALLSEM201617_REGISTRATION/ffcs_login.asp","*://academicscc.vit.ac.in/registrations/FALLSEM_201617_REG/ffcs_login.asp","*://academics2.vit.ac.in/online_withdraw/","*://academics.vit.ac.in/onlinepay/","*://academicscc.vit.ac.in/onlinepay/","*://academics.vit.ac.in/online_application/nridirectug/signin.asp","*://academics.vit.ac.in/online_application/nridirectug/","*://academics2.vit.ac.in/vitmee_results/","*://academics2.vit.ac.in/mscresults/","*://academics2.vit.ac.in/mse_results/","*://academics.vit.ac.in/studentprofile/","*://academics.vit.ac.in/online_application/foreign_btech/default.asp","*://peopleorbit.vit.ac.in/","*://academics.vit.ac.in/online_application/VITMEE/apply.asp","*://academics.vit.ac.in/online_application/UG/apply.asp","*://academics.vit.ac.in/online_application/LAW/application_status.asp","*://academics.vit.ac.in/online_application/UG/application_status.asp","*://academics.vit.ac.in/online_application/nri/register.asp","*://academics.vit.ac.in/fashion/apply.asp","*://academics.vit.ac.in/hotelmgmt/apply.asp","*://academics.vit.ac.in/online_application/BARCH/application_status.asp","*://academics.vit.ac.in/online_application/BARCH/apply.asp","*://academics.vit.ac.in/online_application/LAW/apply.asp","*://vtop.vit.ac.in/student/fresher_2016.asp"]
    }, ["blocking", "responseHeaders"]);
